hipo_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recipes/', include('recipes.urls')),
    url(r'^', include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.conf.urls import url
from . import views

app_name = 'recipes'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create_recipe/$', views.RecipeCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.RecipeDetail.as_view(), name='detail'),
    url(r'update/(?P<pk>[0-9]+)/$', views.RecipeUpdateView.as_view(), name='update'),
    url(r'^like/$', views.like_recipe, name='like'),
    url(r'^rate/$', views.rate_recipe, name='rate'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^$', views.UserFormView.as_view(), name='register'),
    url(r'^log_in/$', auth_views.LoginView.as_view(template_name="users/log_in.html"), name='login'),
    url(r'^log_out/$', auth_views.LogoutView.as_view(template_name="users/log_out.html"), name='logout')
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Avg

class Ingredient(models.Model):
    
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name 

    
class Recipe(models.Model):

    DIFFICULTY_CHOICES = [
        ("e", "Easy"),
        ("m", "Medium"),
        ("a", "Advanced")
    ]

    ingredients = models.ManyToManyField(Ingredient, related_name="recipes")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recipes")
    name = models.CharField(max_length=255)
    image = models.ImageField()
    description = models.TextField()
    date_created = models.DateTimeField(default=timezone.now, editable=False)
    difficulty = models.CharField(max_length=1, choices=DIFFICULTY_CHOICES)
    
    def __str__(self):
        return "{name} by {username}".format(name=self.name, username=self.user.username) 
    
    @property
    def like_count(self):
        return self.likes.count()

    @property
    def ratings_count(self):
        return self.ratings.count()

    @property
    def ratings_avg(self):
        return self.ratings.aggregate(Avg('rate'))['rate__avg'] or 0.0
        
    
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likes")
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="likes")

    class Meta:
        unique_together = ("user", "recipe")


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="ratings")
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="ratings")
    rate = models.IntegerField(default=0, validators=[MaxValueValidator(5),MinValueValidator(0)])

    class Meta:
        unique_together = ("user", "recipe")

    def __str__(self):
        return "{rate} to {recipename}".format(rate=self.rate, recipename=self.recipe.name) 
    

recipes/forms.py
from django import forms
from .models import Recipe


class RecipeForm(forms.ModelForm):

    class Meta:
        model = Recipe
        fields = ['name', 'image', 'description', 'difficulty', 'ingredients']

recipes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.db.models import Count
from django.db.models import Q
from django.urls import reverse
from .models import Recipe, Ingredient, Like, Rating
from .forms import RecipeForm
import operator
from functools import reduce
from django.template.loader import render_to_string
from django.http import JsonResponse


class RecipeCreate(LoginRequiredMixin, generic.CreateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'recipes/recipe_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.user = self.request.user
            recipe.save()
            form.save_m2m()
            return redirect('recipes:index')
        return render(request, self.template_name, {'form': form})


class IndexView(generic.ListView):
    model = Recipe
    template_name = 'recipes/index.html'
    paginate_by = 3

    def get_queryset(self):
        ordering = self.get_ordering()
        queryset = Recipe.objects.all()
        query_string = self.request.GET.get('q')
        
        ingredient_keywords_count = 0
        ingredient_queryset =  queryset

        if query_string is not None:
            for term in query_string.split():
                ingredient_queryset = ingredient_queryset.filter(Q(ingredients__name__in=[term.strip()]))
                if ingredient_queryset.exists():
                    ingredient_keywords_count += 1

            if ingredient_keywords_count > 1:
                queryset = ingredient_queryset
            else:               
                lookups = reduce(operator.or_, (  
                            Q(name__icontains=term.strip()) |
                            Q(description__icontains=term.strip()) |
                            Q(ingredients__name__icontains=term.strip()) for term in query_string.split()
                            )
                        )
                
                queryset = queryset.filter(lookups).distinct()
            
        return queryset.order_by('-date_created')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['top_ingredients'] = Ingredient.objects.annotate(recipes_count=Count('recipes')).order_by("-recipes_count")[:5]
        context['recipes_count'] = Recipe.objects.count()
        return context

    
class RecipeDetail(generic.DetailView):
    model = Recipe
    template_name = 'recipes/recipe_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['was_liked'] = Like.objects.filter(recipe=self.object, user=self.request.user)
        return context


class RecipeUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'recipes/recipe_update.html'
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        recipe = self.get_object()
        return self.request.user == recipe.user
    
    def get_success_url(self):
        return reverse('recipes:detail', kwargs={'pk': self.object.pk,})


def like_recipe(request):
    pk = request.POST.get('id')
    recipe = get_object_or_404(Recipe, pk=pk)
    user = request.user
    like, created = Like.objects.get_or_create(recipe=recipe, user=user)

    if not created:
        like.delete()

    context = {
        'recipe': recipe,
        'was_liked': created
    }
    if request.is_ajax():
        html = render_to_string('recipes/like_template.html', context, request=request)
        return JsonResponse({'form': html})


def rate_recipe(request):
    pk = request.POST.get('id')
    rate = request.POST.get('rate')
    recipe = get_object_or_404(Recipe, pk=pk)
    user = request.user
    rating, created = Rating.objects.get_or_create(recipe=recipe, user=user, defaults={'rate':rate})

    if not created:
        rating.rate = rate
        Rating.objects.filter(recipe=recipe, user=user).update(rate=rate)
    
    # import pdb;pdb.set_trace()
    context = {
        'recipe': recipe,
        'was_rated': created,
        'rate': rate,
    }
    if request.is_ajax():
        html = render_to_string('recipes/rate_template.html', context, request=request)
        return JsonResponse({'form': html})
    

recipes/templates/recipes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Recipe.com{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'recipes:index' %}">Recipe.com <span class="sr-only">(current)</span></a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'recipes:create' %}">Share a Recipe</a>
        </li>
        {% endif %}
      </ul>
      <form action="{% url 'recipes:index' %}" class="form-inline my-2 my-lg-0" method="get">
        <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>      
      <ul class="navbar-nav mr-right">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout ({{user.username}})         
          </a>
        </li>
        {% endif %}
      </ul>    
    </div>
  </nav>
  <br>

{% block body %}
{% endblock %}


</body>
</html>

recipes/templates/recipes/form_template.html
{% load crispy_forms_tags %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="cancel" class="btn btn-light">Cancel</button>
    <br></br>
  </form>

recipes/templates/recipes/index.html
{% extends 'recipes/base.html' %}

{% block body %}

{%for recipe in object_list %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header"> <h3>{{recipe.name}}</h3></div>
                <div class="card-body">
                    <div class="col-md-5" style="padding-left: 0"> <img src="{{ recipe.image.url }}" class="card-img-top"> </div>
                    <br> </br>
                    <p class="card-text">{{ recipe.description }}</p> 
                    <p class="card-text">
                        <h6 class="text-muted"> {{ recipe.date_created|date:"F/d/Y" }} | by {{ recipe.user }} |  {{ recipe.like_count }} like{{ recipe.like_count|pluralize }}
                            |  {{ recipe.ratings_count }} rating{{ recipe.ratings_count|pluralize }} | {{ recipe.ratings_avg }}/5 
                        </h6>
                    </p>
                    <a href="{% url 'recipes:detail' recipe.id %}" class="stretched-link">More...</a>
                </div>
            </div>
        </div>
        {% if forloop.first %}
            <div class="pull-right" style="position: absolute; right:100px;">
                <div class="card" style="max-width: 18rem; border-radius: 25px; ">
                    <div class="card-body">
                        <h4 class="text-center"> Top Used Ingredients</h4><br>
                        <ul>
                            {% for ingredient in top_ingredients %}
                            <li>
                                {{ ingredient.name }} ({{ ingredient.recipes_count }})
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>    

<br></br>
{% endfor %}
<div class="row d-flex justify-content-center">
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <h6 class="text-center">
            <span class="current" >
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.;
            </span> 
            </h6>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-dark">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-dark">last &raquo;</a>
            {% endif %}
           
        </span>

    </div>
   
</div>

<div class="text-center">
    <small>
        Total: {{ recipes_count}} recipes
    </small>
</div>
{% endblock %}

recipes/templates/recipes/like_template.html
{% if request.user.is_authenticated %}
<form action="{% url 'recipes:like' %}" method="post">
  {% csrf_token %}
  {% if was_liked %}
    <button type="submit" id="like" name="recipe_id" value="{{ recipe.id }}" class="btn btn-danger">Dislike</button>
  {% else %}
    <button type="submit" id="like" name="recipe_id" value="{{ recipe.id }}" class="btn btn-primary">Like ({{ recipe.like_count }}) </button>
  {% endif %}
</form>
{% endif %}

recipes/templates/recipes/rate_template.html
{% if user.is_authenticated %}

<form action="{% url 'recipes:rate' %}" method="POST"> 
        {% csrf_token %}      
        <select id="ratings">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
        </select>
        <button id="rate" value="{{ recipe.id }}" type="button" class="btn btn-primary">Rate</button>
</form>
{% endif %}

recipes/templates/recipes/recipe_detail.html
{% extends 'recipes/base.html' %}
{% block title %}Recipe Detail{% endblock %}

{% block body %}
<script>

    $(document).on('click', '#like', function(event){
              event.preventDefault();
              var pk = $(this).attr('value');
              $.ajax({
                type: 'POST',
                url: "{% url 'recipes:like' %}",
                data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: 'json',
                success: function(response){
                  $('#like-template').html(response['form'])
                  console.log($('#like-template').html(response['form']));
                },
                error: function(rs, e){
                  console.log(rs.responseText);
                },
              });
            });
    
    $(document).on('click', '#rate', function(event){
        event.preventDefault();
        var pk = $(this).attr('value');
        var rate = parseInt($("#ratings option:selected").val())
        console.log(rate);
        $.ajax({
        type: 'POST',
        url: "{% url 'recipes:rate' %}",
        data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}', 'rate': rate},
        dataType: 'json',
        success: function(response){
            $('#rate-template').html(response['form'])
            console.log($('#rate-template').html(response['form']));
        },
        error: function(rs, e){
            console.log(rs.responseText);
        },
        });
    });
  
  </script>

<div class="col-sm-5 col-md-6">
    
    <h2> {{recipe.name}} 
        {% if recipe.user == user %}
            <a href="{% url 'recipes:update' recipe.id %}" class="btn btn-outline-dark">Edit</a> 
        {% endif %}
    </h2>
    <h6>
        <i class="em em-female-cook" aria-role="presentation" aria-label="female-cook"></i>
        {{recipe.user}}&nbsp;
        <i class="em em-muscle" aria-role="presentation" aria-label="muscle"></i>
        {{recipe.get_difficulty_display}}&nbsp;&nbsp;
        <i class="em em-clock1" aria-role="presentation" aria-label="clock1"></i>
        {{ recipe.date_created|date:"F/d/Y" }}
    </h6>
    <div class="col-md-5" style="padding-left: 0"> <img src="{{ recipe.image.url }}" class="card-img-top"></div>
    <br>
    <div id="like-template">
        {% include 'recipes/like_template.html' %}
    </div>
    <br>
    <h4> Ingredients </h4>
    <ul>
        {% for ingredient in recipe.ingredients.all %}
            <li>{{ingredient.name}}</li>
        {% endfor%}
    </ul>
    <h4> Description </h4>
    <p>
        {{recipe.description}}
    </p>
    <div id="rate-template">
        {% include 'recipes/rate_template.html' %}
    </div>
</div>

{% endblock %}

recipes/templates/recipes/recipe_form.html
{% extends 'recipes/base.html' %}
{% block title %}Add a New Recipe{% endblock %}


{% block body %}
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <div class="col-sm-12 col-md-14">
        <h3 class=text-center>Add a New Recipe</h3>
        {% include 'recipes/form_template.html' %}
    </div>

{% endblock %}

recipes/templates/recipes/recipe_update.html
{% extends 'recipes/base.html' %}
{% block title %}Edit Recipe{% endblock %}


{% block body %}

    <div class="col-sm-12 col-md-14">
        <h3 class=text-center>Edit Recipe</h3>
        {% include 'recipes/form_template.html' %}
    </div>

{% endblock %}