hipo_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recipes/', include('recipes.urls')),
    url(r'^', include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^$', views.UserFormView.as_view(), name='register'),
    url(r'^log_in/$', auth_views.LoginView.as_view(template_name="users/log_in.html"), name='login'),
    url(r'^log_out/$', auth_views.LogoutView.as_view(template_name="users/log_out.html"), name='logout')
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from .forms import UserForm

class UserFormView(View):
    form_class = UserForm
    template_name = 'users/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('recipes:index')

        return render(request, self.template_name, {'form': form})

users/templates/users/log_in.html
{% extends 'recipes/base.html' %}
{% block title %}Log in{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}

<div class="col-sm-12 col-md-6">
    <h3 text-center>Log in</h3>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'recipes/form_template.html' %}
    </form>
    <div class="panel-footer">
        Don't have an account? <a href="{% url 'users:register' %}">Click here</a> to register.
    </div>
           
</div>
 
{% endblock %}

users/templates/users/log_out.html
{% extends 'recipes/base.html' %}
{% block title %}Log in again{% endblock %}
{% block register_active %}active{% endblock %}

{% block body%}

<h3>
    Missed us? <a href="{% url 'users:login' %}">Click here</a> to log in again.
</h3>

{% endblock %}

users/templates/users/registration_form.html
{% extends 'recipes/base.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}

<div class="col-sm-12 col-md-6">
    <h3 text-center>Register for an Account</h3>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'recipes/form_template.html' %}
    </form>
    <div class="panel-footer">
        Already have an account? <a href="{% url 'users:login' %}">Click here</a> to log in.
    </div>
           
</div>
 
{% endblock %}